kind: pipeline
type: docker
name: default

steps:
- name: build and test
  image: golang:1.19
  environment:
    CGO_ENABLED: no
  commands:
  - go mod download
  - go build
  - go test

- name: release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_pass
    base_url: https://git.merkulov.online
    files:
    - kafka-tools
  when:
    ref:
    - refs/tags/**

trigger:
  refs:
  - refs/heads/master
  - refs/pull/*/head
  - refs/tags/**

